tagFormat: "${version}"
repositoryUrl: https://github.com/masoudn84/iac_jenkins.git
branches:
    - "+([0-9])?(.{+([0-9]),x}).x"
    - "main"
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - "@semantic-release/github"
    - "@semantic-release/git"
assets:
    - CHANGELOG.md
